### ISSUE TITLE
可以支持自动提交审核，自动发布吗？

### ISSUE THREAD

**Issue by sunnywanggit** [lxchuan12/mini-ci#2]

**Comment by ruochuan12** [comment]
[miniprogram-ci](https://developers.weixin.qq.com/miniprogram/dev/devtools/ci.html) 未提供这样的能力。

第三方平台方式才提供了这样的接口。
[提交代码审核](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/code-management/submitAudit.html)
