### ISSUE TITLE
请问如果修改显示的界面？

### ISSUE THREAD

**Issue by zimuyun** [lxchuan12/mini-ci#3]
1。你好，请问如何修改显示的界面？现在的字体有点小，选中的样式不是很清晰。在/usr/local/lib/node_modules/@ruochuan/mini-ci中没找到相应的代码。
<img width="548" alt="image" src="https://github.com/lxchuan12/mini-ci/assets/17318464/ce1f8f1c-ff1f-435a-8956-06ad17778b5b”>
2。如何修改代码或可否增加一个功能，小程序上传成功后，访问一个api接口，可传递小程序的appid和体验版的预览的二维码。谢谢。

**Comment by ruochuan12** [comment]
1. 感谢使用~选择这个主要使用的 npm 包是[enquirer](https://github.com/enquirer/enquirer)。选择和取消选择，是使用空格键来操作的，选中后前面的箭头会高亮。可能在你的终端是白色的导致选中的样式不够清晰。另外可以调整你的终端字体大小、调整终端颜色为黑色。来解决这个问题。
2. 非常好的建议，我已经添加了这个功能，你可以使用最新版本查看体验。另外，其实我的  mini-ci 这个支持配置插件。

```js
export default {
         // 省略其他配置...
         // 插件机制 可选
	plugins: [
		/**
		{
			name: '操作前',
			// 操作前
			enforce: 'pre',
			handler: (config) => {
				console.log('准备操作...', config);
			},
		},
		{
			name: '操作中',
			handler: (config) => {
				console.log('操作中...', config);
			},
		},
		{
			name: '操作后',
			enforce: 'post',
			handler: (config) => {
				console.log('操作完成...', config);
			},
		},
		 */
	],
}
```
更多配置可以查看这个 [mini.config.js](https://github.com/lxchuan12/mini-ci/blob/main/packages/mini-ci/mini.config.js) 文件。

参考代码生成二维码的

```js
// npm i qrcode -D
import * as QRCode from 'qrcode';
const printQrcode = async (url) => {
  let terminalStr = await QRCode.toString(url, { type: 'terminal', small: true });
  console.log(terminalStr);
};

// 生成二维码并输出到控制台
const url = 'https://open.weixin.qq.com/sns/getexpappinfo?appid=xxx#wechat-redirect';
printQrcode(url);
```

你可以在 plugins 操作后 `enforce: 'post',` 自行开发插件，或者其他自定义功能。或者就保存特定的几个小程序体验版的链接。

`https://open.weixin.qq.com/sns/getexpappinfo?appid=xxx#wechat-redirect`

如果后续有问题，欢迎继续交流。或者加微信：`lxchuan12`。

**Comment by zimuyun** [comment]
好的，十分感谢。
